# Generated by Django 5.0.4 on 2024-04-11 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
                ('from_email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
