# Generated by Django 5.0.4 on 2024-04-12 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususers',
            name='from_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Your email address:'),
        ),
        migrations.AlterField(
            model_name='anonymoususers',
            name='message',
            field=models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Your message:'),
        ),
        migrations.AlterField(
            model_name='anonymoususers',
            name='your_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Your name:'),
        ),
    ]
