# Generated by Django 5.0.4 on 2024-04-10 16:35

import datetime
import django.db.models.deletion
import online_book_shop.books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[online_book_shop.books.validators.validate_title_min])),
                ('author', models.CharField(max_length=30, validators=[online_book_shop.books.validators.validate_author_min])),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('publication_date', models.DateTimeField(default=datetime.datetime.now)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('action', 'Action'), ('crime', 'Crime'), ('western', 'Western'), ('autobiography', 'Autobiography')], max_length=13)),
                ('cover', models.URLField(error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, unique=True, verbose_name='Image URL')),
                ('book_owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bookshopuser')),
            ],
        ),
    ]
